name: Build Flutter APK

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.2.2

      - name: Configurar Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.41.7 --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Restaurar servicios privados
        run: |
          echo "${{ secrets.F95_SERVICE }}" | base64 --decode > frontend/lib/services/f95_service.dart
          echo "${{ secrets.F95_CONFIG_SCREEN }}" | base64 --decode > frontend/lib/screens/f95_config_screen.dart
          
      - name: Instalar dependencias
        working-directory: frontend
        run: flutter pub get

      - name: Build APK release
        working-directory: frontend
        run: flutter build apk --release

      - name: Renombrar APK
        run: mv frontend/build/app/outputs/flutter-apk/app-release.apk feed95.apk

      - name: Borrar Release 'beta' anterior
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: beta-android
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear Pre-release 'beta'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: beta-android
          name: "Feed95 - Versión Beta (Android)"
          body: "Versión beta de la aplicación para Android."
          # Para que sea un lanzamiento oficial solo debo cambiar el prerelease a false
          prerelease: true
          files: feed95.apk
          token: ${{ secrets.GITHUB_TOKEN }}