name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.41.7 --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Instalar dependencias
        working-directory: frontend
        run: flutter pub get

      - name: Build APK release
        working-directory: frontend
        run: flutter build apk --release

      - name: Renombrar APK
        # Renombramos el archivo a "feed95.apk" exactamente
        run: mv frontend/build/app/outputs/flutter-apk/app-release.apk frontend/build/app/outputs/flutter-apk/feed95.apk

      - name: Crear Pre-release en GitHub
        uses: softprops/action-gh-release@v2
        with:
          # Nombre del tag y del Release (v0.1) antes creaba uno automatico y eso no estaba chimbita
          tag_name: "v0.1"
          name: "Feed95 v0.1"
          body: "Nueva versión de prueba de Feed95. Descarga e instala el archivo feed95.apk."
          # Esto lo pongo para que aparezca como Pre-release
          prerelease: true
          # Este es el archivo que se subirá
          files: frontend/build/app/outputs/flutter-apk/feed95.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}