name: Build Flutter APK

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.2.2

      - name: Configurar Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.41.7 --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Instalar dependencias
        working-directory: frontend
        run: flutter pub get

      - name: Build APK release
        working-directory: frontend
        run: flutter build apk --release

      - name: Renombrar APK
        run: mv frontend/build/app/outputs/flutter-apk/app-release.apk feed95.apk

      - name: Borrar Release anterior
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: v1.0.0-android
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear Release v1.0.0
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0-android
          name: "Feed95 v1.0.0 (Android)"
          body: "Primera versión oficial de Feed95 para Android."
          prerelease: false
          files: feed95.apk
          token: ${{ secrets.GITHUB_TOKEN }}