name: Build Flutter Windows EXE

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/build-exe.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.2.2

      - name: Configurar Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.41.7 --depth 1 $env:USERPROFILE\flutter
          echo "$env:USERPROFILE\flutter\bin" >> $env:GITHUB_PATH

      - name: Instalar dependencias
        working-directory: frontend
        run: flutter pub get

      - name: Habilitar soporte Windows
        working-directory: frontend
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        working-directory: frontend
        run: flutter build windows --release

      - name: Comprimir ejecutable
        # Al renombrar el binario en CMakeLists, el ejecutable ya se llamará feed95.exe
        run: |
          Compress-Archive -Path "frontend\build\windows\x64\runner\Release\*" -DestinationPath "feed95.zip"

      - name: Borrar Release anterior
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: v1.0.0-windows
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear Release v1.0.0
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0-windows
          name: "Feed95 v1.0.0 (Windows)"
          body: "Primera versión oficial de Feed95 para Windows."
          prerelease: false
          files: feed95.zip
          token: ${{ secrets.GITHUB_TOKEN }}