name: Build Flutter Windows EXE

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/build-exe.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.2.2

      - name: Configurar Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.41.7 --depth 1 $env:USERPROFILE\flutter
          echo "$env:USERPROFILE\flutter\bin" >> $env:GITHUB_PATH

      - name: Restaurar servicios privados
        shell: pwsh
        run: |
          [System.IO.File]::WriteAllBytes("frontend/lib/services/f95_service.dart", [System.Convert]::FromBase64String("${{ secrets.F95_SERVICE }}"))
          [System.IO.File]::WriteAllBytes("frontend/lib/screens/f95_config_screen.dart", [System.Convert]::FromBase64String("${{ secrets.F95_CONFIG_SCREEN }}"))

      - name: Instalar dependencias
        working-directory: frontend
        run: flutter pub get

      - name: Habilitar soporte Windows
        working-directory: frontend
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        working-directory: frontend
        run: flutter build windows --release

      - name: Comprimir ejecutable
        # Al renombrar el binario en CMakeLists, el ejecutable ya se llamará feed95.exe
        run: |
          Compress-Archive -Path "frontend\build\windows\x64\runner\Release\*" -DestinationPath "feed95.zip"

      - name: Borrar Release 'beta' anterior
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: beta-windows
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear Pre-release 'beta'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: beta-windows
          name: "Feed95 - Versión Beta (Windows)"
          body: "Versión beta de la aplicación para Windows."
          # Para que sea un lanzamiento oficial solo debo cambiar el prerelease a false
          prerelease: true
          files: feed95.zip
          token: ${{ secrets.GITHUB_TOKEN }}